[tool.poetry]
name = "plsim"
version = "0.1.0"
description = "Esimation and Inference for PLSIM"
authors = ["Haozhen Shu"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
